project_id = "vdqucrjsypcmsqzpibsz"

[functions.jarvis-chat]
verify_jwt = false

[functions.jarvis-tts]
verify_jwt = false

[functions.jarvis-whatsapp-twilio]
verify_jwt = false

[functions.realtime-token]
verify_jwt = false
